name: Build OT RCP firmware

on:
  workflow_dispatch:
    inputs:
      help:
        type: boolean
        description: "Display help for various commands"
        required: false
      debug:
        type: boolean
        description: "Output build data to artifacts"
        required: false
  release:
    types:
      - published

env:
  SYSCFG_ROOT: /opt/ti/sysconfig_1.24.1
  OT_SDK_PATH: /opt/ot-ti
  F2_SDK_PATH: /opt/simplelink-lowpower-f2-sdk
  F3_SDK_PATH: /opt/simplelink-lowpower-f3-sdk
  TICLANG_PATH: /opt/ti-cgt-armllvm_4.0.4.LTS

jobs:
  build_container:
    name: Call
    uses: ./.github/workflows/build-container.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit

  build_firmwares:
    name: Build OT RCP firmware
    needs: [build_container]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ${{ needs.build_container.outputs.container_name }}
      options: --user root
    strategy:
      matrix:
        include:
          - name: CC26X2R1_LAUNCHXL
          - name: CC1352P_2_LAUNCHXL
          - name: CC1352P_2_other
            board_name: CC1352P_2_LAUNCHXL
            other: true
          - name: LP_CC1352P7_4
          - name: LP_CC2652R7
          - name: LP_CC2652RB
          # - name: LP_EM_CC2674P10
          - name: LP_EM_CC2340R53
    steps:
      - uses: actions/checkout@v5

      # Fix `fatal: detected dubious ownership in repository at`
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - run: tree -d /opt
        if: ${{ inputs.help }}

      - name: Apply SDK patches
        run: |
          echo "Setting build date"
          now=$(date +"%Y%m%d")

          sed -i -e "s+OT_PACKAGE_VERSION \"1.4.0.0\"+OT_PACKAGE_VERSION \"1.4.0.0-$now\"+g" ${{ env.OT_SDK_PATH }}/CMakeLists.txt

      - name: Patch syscfg
        run: |
          cat $PWD/syscfg/ot-rcp/all.syscfg.js >> ${{ env.OT_SDK_PATH }}/src/openthread.syscfg
          cat $PWD/syscfg/ot-rcp/${{ matrix.name }}.syscfg.js >> ${{ env.OT_SDK_PATH }}/src/openthread.syscfg
          cat $PWD/syscfg/ot-rcp/all.syscfg.js >> ${{ env.OT_SDK_PATH }}/src/cc23xx_cc27xx/openthread.syscfg
          cat $PWD/syscfg/ot-rcp/${{ matrix.name }}.syscfg.js >> ${{ env.OT_SDK_PATH }}/src/cc23xx_cc27xx/openthread.syscfg

      # XXX: this is nasty (patch to patch to patch...)
      - name: Patch "other" mid-build
        if: ${{ matrix.other }}
        run: |
          chmod +x $PWD/syscfg/ot-rcp_CC1352P_2_other/script.build-patch.sh
          chmod +x $PWD/syscfg/ot-rcp_CC1352P_2_other/ti_drivers_config.h-patch.sh
          sed -i -e "s+-B \${builddir}+-B \${builddir}\n    $PWD/syscfg/ot-rcp_CC1352P_2_other/script.build-patch.sh+g" ${{ env.OT_SDK_PATH }}/script/build

      - name: Build firmware
        run: |
          cd ${{ env.OT_SDK_PATH }}
          TI_SYSCONFIG_ROOT=${{ env.SYSCFG_ROOT }} ./script/build ${{ matrix.board_name || matrix.name }}

      - name: Create firmware hex
        run: ${{ env.TICLANG_PATH }}/bin/tiarmobjcopy ${{ env.OT_SDK_PATH }}/build/bin/ot-rcp.out --output-target ihex ${{ env.OT_SDK_PATH }}/build/bin/openthread_${{ matrix.name }}.hex

      - uses: actions/upload-artifact@v5
        if: ${{ inputs.debug }}
        with:
          name: build_dir_${{ matrix.name }}
          path: |
            ${{ env.OT_SDK_PATH }}/build/
            !${{ env.OT_SDK_PATH }}/build/**/*.a
            !${{ env.OT_SDK_PATH }}/build/**/*.obj
            !${{ env.OT_SDK_PATH }}/build/**/*.lib
            !${{ env.OT_SDK_PATH }}/build/**/*.bin
          include-hidden-files: true

      - uses: actions/upload-artifact@v5
        with:
          name: firmware_build_${{ matrix.name }}
          path: ${{ env.OT_SDK_PATH }}/build/bin/*.hex

  release-assets:
    name: Upload release assets
    needs: [build_firmwares]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download firmware builds artifact
        uses: actions/download-artifact@v6
        with:
          pattern: firmware_build_*
          path: artifacts
          merge-multiple: true

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.hex
