name: Print zstack SysConfig defaults

on:
  workflow_dispatch:

# copy from build-zstack
env:
  CCS_CMD: /opt/ccs/eclipse/eclipse -noSplash -data /opt/simplelink_cc13xx_cc26xx_sdk_8_30_01_01/workspace
  CCS_INIT: -application com.ti.ccstudio.apps.initialize
  CCS_INSPECT: -application com.ti.ccstudio.apps.inspect
  CCS_CREATE: -application com.ti.ccstudio.apps.createProject
  CCS_IMPORT: -application com.ti.ccstudio.apps.importProject
  CCS_MODIFY: -application com.ti.ccstudio.apps.modifyProject
  CCS_BUILD: -application com.ti.ccstudio.apps.buildProject
  SYSCFG_CLI: /opt/sysconfig_1.21.1/sysconfig_cli.sh
  SDK_PATH: /opt/simplelink_cc13xx_cc26xx_sdk_8_30_01_01
  PROJECT_DEFAULTS: -ccs.endianness little -ccs.toolChain TICLANG -ccs.toolVersion TICLANG_4.0.2.LTS -ccs.outputType executable -ccs.setPostBuildStep "${CG_TOOL_ROOT}/bin/tiarmobjcopy ${BuildArtifactFileName} --output-target ihex ${BuildArtifactFileBaseName}.hex;" -ccs.linkFile /opt/simplelink_cc13xx_cc26xx_sdk_8_30_01_01/source/preinclude.h -ccs.linkFile /opt/simplelink_cc13xx_cc26xx_sdk_8_30_01_01/source/ti/zstack/stack/nwk/nwk_util.c

jobs:
  build_container:
    name: Call
    uses: ./.github/workflows/build-container.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit

  print:
    name: Print zstack SysConfig defaults
    needs: [build_container]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ${{ needs.build_container.outputs.container_name }}
      options: --user root
    steps:
      - uses: actions/checkout@v5

      # Fix `fatal: detected dubious ownership in repository at`
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Create project znp_CC1352P_2_LAUNCHXL_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/CC1352P_2_LAUNCHXL/zstack/znp/tirtos7/ticlang/znp_CC1352P_2_LAUNCHXL_tirtos7_ticlang.projectspec -ccs.name znp_CC1352P_2_LAUNCHXL_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_COORDINATOR"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/znp_CC1352P_2_LAUNCHXL_tirtos7_ticlang/znp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/znp_CC1352P_2_LAUNCHXL_tirtos7_ticlang/znp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project znp_CC1352P_2_other_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/CC1352P_2_LAUNCHXL/zstack/znp/tirtos7/ticlang/znp_CC1352P_2_LAUNCHXL_tirtos7_ticlang.projectspec -ccs.name znp_CC1352P_2_other_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_COORDINATOR -UCONFIG_RF_24GHZ -DCONFIG_RF_24GHZ=6 -UCONFIG_RF_HIGH_PA -DCONFIG_RF_HIGH_PA=5"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/znp_CC1352P_2_other_tirtos7_ticlang/znp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/znp_CC1352P_2_other_tirtos7_ticlang/znp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project znp_CC26X2R1_LAUNCHXL_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/CC26X2R1_LAUNCHXL/zstack/znp/tirtos7/ticlang/znp_CC26X2R1_LAUNCHXL_tirtos7_ticlang.projectspec -ccs.name znp_CC26X2R1_LAUNCHXL_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_COORDINATOR"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/znp_CC26X2R1_LAUNCHXL_tirtos7_ticlang/znp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/znp_CC26X2R1_LAUNCHXL_tirtos7_ticlang/znp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project znp_LP_CC1352P7_4_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/LP_CC1352P7_4/zstack/znp/tirtos7/ticlang/znp_LP_CC1352P7_4_tirtos7_ticlang.projectspec -ccs.name znp_LP_CC1352P7_4_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_COORDINATOR"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/znp_LP_CC1352P7_4_tirtos7_ticlang/znp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/znp_LP_CC1352P7_4_tirtos7_ticlang/znp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project znp_LP_CC2652R7_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/LP_CC2652R7/zstack/znp/tirtos7/ticlang/znp_LP_CC2652R7_tirtos7_ticlang.projectspec -ccs.name znp_LP_CC2652R7_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_COORDINATOR"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/znp_LP_CC2652R7_tirtos7_ticlang/znp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/znp_LP_CC2652R7_tirtos7_ticlang/znp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project znp_LP_CC2652RB_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/LP_CC2652RB/zstack/znp/tirtos7/ticlang/znp_LP_CC2652RB_tirtos7_ticlang.projectspec -ccs.name znp_LP_CC2652RB_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_COORDINATOR"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/znp_LP_CC2652RB_tirtos7_ticlang/znp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/znp_LP_CC2652RB_tirtos7_ticlang/znp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project znp_LP_EM_CC2674P10_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/LP_EM_CC2674P10/zstack/znp/tirtos7/ticlang/znp_LP_EM_CC2674P10_tirtos7_ticlang.projectspec -ccs.name znp_LP_EM_CC2674P10_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_COORDINATOR"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/znp_LP_EM_CC2674P10_tirtos7_ticlang/znp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/znp_LP_EM_CC2674P10_tirtos7_ticlang/znp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project zr_genericapp_CC1352P_2_LAUNCHXL_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/CC1352P_2_LAUNCHXL/zstack/zr_genericapp/tirtos7/ticlang/zr_genericapp_CC1352P_2_LAUNCHXL_tirtos7_ticlang.projectspec -ccs.name zr_genericapp_CC1352P_2_LAUNCHXL_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_ROUTER"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/zr_genericapp_CC1352P_2_LAUNCHXL_tirtos7_ticlang/zr_genericapp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/zr_genericapp_CC1352P_2_LAUNCHXL_tirtos7_ticlang/zr_genericapp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project zr_genericapp_CC1352P_2_other_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/CC1352P_2_LAUNCHXL/zstack/zr_genericapp/tirtos7/ticlang/zr_genericapp_CC1352P_2_LAUNCHXL_tirtos7_ticlang.projectspec -ccs.name zr_genericapp_CC1352P_2_other_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_ROUTER -UCONFIG_RF_24GHZ -DCONFIG_RF_24GHZ=6 -UCONFIG_RF_HIGH_PA -DCONFIG_RF_HIGH_PA=5"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/zr_genericapp_CC1352P_2_other_tirtos7_ticlang/zr_genericapp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/zr_genericapp_CC1352P_2_other_tirtos7_ticlang/zr_genericapp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project zr_genericapp_CC26X2R1_LAUNCHXL_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/CC26X2R1_LAUNCHXL/zstack/zr_genericapp/tirtos7/ticlang/zr_genericapp_CC26X2R1_LAUNCHXL_tirtos7_ticlang.projectspec -ccs.name zr_genericapp_CC26X2R1_LAUNCHXL_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_ROUTER"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/zr_genericapp_CC26X2R1_LAUNCHXL_tirtos7_ticlang/zr_genericapp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/zr_genericapp_CC26X2R1_LAUNCHXL_tirtos7_ticlang/zr_genericapp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project zr_genericapp_LP_CC1352P7_4_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/LP_CC1352P7_4/zstack/zr_genericapp/tirtos7/ticlang/zr_genericapp_LP_CC1352P7_4_tirtos7_ticlang.projectspec -ccs.name zr_genericapp_LP_CC1352P7_4_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_ROUTER"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/zr_genericapp_LP_CC1352P7_4_tirtos7_ticlang/zr_genericapp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/zr_genericapp_LP_CC1352P7_4_tirtos7_ticlang/zr_genericapp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project zr_genericapp_LP_CC2652R7_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/LP_CC2652R7/zstack/zr_genericapp/tirtos7/ticlang/zr_genericapp_LP_CC2652R7_tirtos7_ticlang.projectspec -ccs.name zr_genericapp_LP_CC2652R7_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_ROUTER"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/zr_genericapp_LP_CC2652R7_tirtos7_ticlang/zr_genericapp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/zr_genericapp_LP_CC2652R7_tirtos7_ticlang/zr_genericapp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project zr_genericapp_LP_CC2652RB_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/LP_CC2652RB/zstack/zr_genericapp/tirtos7/ticlang/zr_genericapp_LP_CC2652RB_tirtos7_ticlang.projectspec -ccs.name zr_genericapp_LP_CC2652RB_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_ROUTER"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/zr_genericapp_LP_CC2652RB_tirtos7_ticlang/zr_genericapp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/zr_genericapp_LP_CC2652RB_tirtos7_ticlang/zr_genericapp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang

      - name: Create project zr_genericapp_LP_EM_CC2674P10_tirtos7_ticlang
        run: |
          ${{ env.CCS_CMD }} ${{ env.CCS_CREATE }} -ccs.projectSpec ${{ env.SDK_PATH }}/examples/rtos/LP_EM_CC2674P10/zstack/zr_genericapp/tirtos7/ticlang/zr_genericapp_LP_EM_CC2674P10_tirtos7_ticlang.projectspec -ccs.name zr_genericapp_LP_EM_CC2674P10_tirtos7_ticlang ${{ env.PROJECT_DEFAULTS }} -ccs.setCompilerOptions "${{ env.I_PREINCLUDE }} -DIS_ROUTER"
          cat $PWD/docs/print-defaults-zstack.syscfg.js >> ${{ env.SDK_PATH }}/workspace/zr_genericapp_LP_EM_CC2674P10_tirtos7_ticlang/zr_genericapp.syscfg
          ${{ env.SYSCFG_CLI }} --script ${{ env.SDK_PATH }}/workspace/zr_genericapp_LP_EM_CC2674P10_tirtos7_ticlang/zr_genericapp.syscfg -o syscfg -s ${{ env.SDK_PATH }}/.metadata/product.json --compiler ticlang
